1. Array Creation

NumPy arrays can be created using np.array() or built-in functions like np.zeros(), np.ones(), np.arange(), and more.

In [1]:
import numpy as np

# Creating a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

# Creating a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)


1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


2. Reshaping

Reshaping changes the dimensions of an array using reshape(). The total number of elements must remain constant.

In [2]:

# Reshape 1D to 2D

reshaped = arr1.reshape(1, 5)
print("Reshaped to 2D:\n", reshaped)

# Reshape 2D to 3x2
reshaped_2 = arr2.reshape(3, 2)
print("Reshaped to 3x2:\n", reshaped_2)


Reshaped to 2D:
 [[1 2 3 4 5]]
Reshaped to 3x2:
 [[1 2]
 [3 4]
 [5 6]]


3. Indexing and Slicing

Access specific elements or slices of an array using indexes. Slicing uses : to define ranges.

In [3]:
# Indexing
element = arr2[0, 1]  # Element at row 0, column 1
print("Element at (0,1):", element)

# Slicing
slice_ = arr2[:, 1]  # All rows, second column
print("Slice (all rows, second column):", slice_)


Element at (0,1): 2
Slice (all rows, second column): [2 5]


4. Filtering

Apply boolean conditions to extract elements.

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6])
filtered = arr[arr > 3]  # Filter elements greater than 3
print("Filtered (greater than 3):", filtered)


Filtered (greater than 3): [4 5 6]


5. Element-wise Operations

Perform arithmetic operations directly on arrays.

In [5]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise addition and multiplication
add_result = arr1 + arr2
mult_result = arr1 * arr2

print("Addition Result:", add_result)
print("Multiplication Result:", mult_result)


Addition Result: [5 7 9]
Multiplication Result: [ 4 10 18]


6. Aggregate Functions

Summarize data with functions like np.sum(), np.mean(), np.min(), etc.

In [6]:
matrix = np.array([[1, 2], [3, 4]])

# Sum and mean
total_sum = np.sum(matrix)
row_sum = np.sum(matrix, axis=1)  # Sum across rows

print("Total Sum:", total_sum)
print("Row Sums:", row_sum)


Total Sum: 10
Row Sums: [3 7]


7. Comparison Operations

Compare arrays element-wise and generate boolean arrays.

In [7]:
arr = np.array([10, 20, 30])
comparison = arr > 15
print("Comparison (greater than 15):", comparison)


Comparison (greater than 15): [False  True  True]


Broadcasting
Broadcasting allows operations on arrays of different shapes, aligning smaller arrays to larger ones.

1. Understanding Broadcasting
Smaller arrays are "stretched" to match larger arrays for operations.

In [8]:
arr1 = np.array([[1], [2], [3]])  # Shape (3, 1)
arr2 = np.array([4, 5, 6])       # Shape (3,)

result = arr1 + arr2  # Broadcasting
print("Broadcasted Addition:\n", result)


Broadcasted Addition:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


Real-world Example

Apply normalization (subtract mean) to a dataset using broadcasting.



In [9]:
data = np.array([[1, 2, 3], [4, 5, 6]])

# Subtract the mean of each column
mean = np.mean(data, axis=0)
normalized_data = data - mean

print("Original Data:\n", data)
print("Mean of Columns:", mean)
print("Normalized Data:\n", normalized_data)


Original Data:
 [[1 2 3]
 [4 5 6]]
Mean of Columns: [2.5 3.5 4.5]
Normalized Data:
 [[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]


Exercises to Solidify Learning
Create a 3x3 matrix of random integers and:

Extract the diagonal elements.
Find the mean of each row.
Normalize a 4x4 matrix by subtracting its mean and dividing by its standard deviation.

Create a 2D array (shape 3x3) and broadcast a 1D array (shape 3,) to add it.

By practicing and reviewing these examples and exercises, you'll build a strong understanding of NumPy basics and be ready for advanced topics.

In [10]:
import numpy as np

# Create a 3x3 matrix with random integers between 1 and 10
matrix = np.random.randint(1, 11, (3, 3))
print("3x3 Matrix:\n", matrix)

# Extract the diagonal elements
diagonal = np.diag(matrix)
print("Diagonal Elements:", diagonal)

# Find the mean of each row
row_means = np.mean(matrix, axis=1)
print("Mean of Each Row:", row_means)


# Create a 4x4 matrix with random integers between 1 and 20
matrix_4x4 = np.random.randint(1, 21, (4, 4))
print("Original 4x4 Matrix:\n", matrix_4x4)

# Calculate the mean and standard deviation of the entire matrix
mean = np.mean(matrix_4x4)
std_dev = np.std(matrix_4x4)

# Normalize the matrix
normalized_matrix = (matrix_4x4 - mean) / std_dev
print("Normalized 4x4 Matrix:\n", normalized_matrix)


# Create a 2D array of shape 3x3
matrix_2D = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
print("2D Array (3x3):\n", matrix_2D)

# Create a 1D array of shape (3,)
array_1D = np.array([10, 20, 30])
print("1D Array:", array_1D)

# Broadcast and add the 1D array to the 2D array
broadcasted_sum = matrix_2D + array_1D
print("Result of Broadcasting and Adding:\n", broadcasted_sum)


3x3 Matrix:
 [[10  9  1]
 [ 4  6  6]
 [10  1  3]]
Diagonal Elements: [10  6  3]
Mean of Each Row: [6.66666667 5.33333333 4.66666667]
Original 4x4 Matrix:
 [[15  2  7  8]
 [14 14 12  3]
 [18 14 16  1]
 [15 15  3 15]]
Normalized 4x4 Matrix:
 [[ 0.76102452 -1.56681518 -0.67149222 -0.49242763]
 [ 0.58195993  0.58195993  0.22383074 -1.38775059]
 [ 1.2982183   0.58195993  0.94008911 -1.74587978]
 [ 0.76102452  0.76102452 -1.38775059  0.76102452]]
2D Array (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
1D Array: [10 20 30]
Result of Broadcasting and Adding:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]
